# Generated by Django 4.0.6 on 2022-07-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('big_num', 'big_num'), ('small_num', 'small_num')], max_length=20),
        ),
    ]
