# Generated by Django 4.0.6 on 2022-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_remove_game_tie_flag_alter_game_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('big_num', 'big_num'), ('small_num', 'small_num')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('proceed', 'proceed'), ('end', 'end')], max_length=20),
        ),
    ]
