# Generated by Django 4.0.6 on 2022-07-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_alter_game_game_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tie_flag',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('small_num', 'small_num'), ('big_num', 'big_num')], max_length=20),
        ),
    ]
