# Generated by Django 4.0.6 on 2022-07-21 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0003_alter_game_game_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='defenser',
        ),
        migrations.AddField(
            model_name='game',
            name='defender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='defense_card',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('proceed', 'proceed'), ('end', 'end')], max_length=20),
        ),
    ]
