# Generated by Django 4.0.6 on 2022-07-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0004_remove_game_defenser_game_defender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='defense_card',
            new_name='defend_card',
        ),
        migrations.AlterField(
            model_name='game',
            name='attack_card',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
