# Generated by Django 4.0.6 on 2022-07-21 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0005_rename_defense_card_game_defend_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defend_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defender', to=settings.AUTH_USER_MODEL),
        ),
    ]
