# Generated by Django 3.2.14 on 2022-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0005_auto_20220722_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('end', 'end'), ('proceed', 'proceed')], max_length=20),
        ),
    ]
