# Generated by Django 3.2.14 on 2022-07-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0006_alter_game_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attack_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='defend_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('small_num', 'small_num'), ('big_num', 'big_num')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('proceed', 'proceed'), ('end', 'end')], max_length=20),
        ),
    ]
