# Generated by Django 4.0.6 on 2022-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0008_alter_game_attack_card_alter_game_defend_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tie_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('big_num', 'big_num'), ('small_num', 'small_num')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('end', 'end'), ('proceed', 'proceed')], max_length=20),
        ),
    ]
