# Generated by Django 4.0.6 on 2022-07-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0009_game_tie_flag_alter_game_game_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('small_num', 'small_num'), ('big_num', 'big_num')], max_length=20),
        ),
    ]
